### ISSUE TITLE
Enroll crashes with more than 14 friends

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#168]
Enroll plugin, if there are many (in my case 14) friends, the "edit friends info" page will crash on .Net side.

**Comment by mbehrooz** [comment]
I followed up on this and the bug is unrelated to number of people in owl, but to their names and if there is an empty string because .Net does not accept empty strings for buttons. It is not a bug since we prevent empty strings in enroll now, I believe it was added before I add the empty check to my ontology file. I got a fresh user.owl and it is ok.
