### ISSUE TITLE
Enroll bug

### ISSUE THREAD

**Issue by candysidner** [always-on/always#189]
Enroll somehow assigns "wife" instead of spouse as value of relationship for enrolling the user.  If you can't find code that does this, it may be that some code value remembers wife from the previous write to the UM (the time before the current run I added a person who had a spouse who was female).

**Comment by mbehrooz** [comment]
This is definitely not caused by Enroll in my opinion, which is to say it must be caused by ontology, I checked person.owl file and it does not seem to be using Wife where not supposed to. That led me to check PeopleManager and other classes, also the process in which spouse is saved from Enroll through Ontology classes. All seems correct. I double checked by actually entering a spouse and looking into User.owl. I entered "Dave" and entered "lindak" (running outta names!) as spouse. The following comment is the lines in User.owl which it seems correct:

**Comment by mbehrooz** [comment]
+ClassAssertion(<#MalePerson> <#Dave>)
+ClassAssertion(<#Person> <#Dave>)
+ObjectPropertyAssertion(<#Friend> <#Dave> <#Diane%20Ferguson>)
+ObjectPropertyAssertion(<#PersonLivesIn> <#Dave> <#55555>)
+ObjectPropertyAssertion(<#Spouse> <#Dave> <#Lindik>)
+DataPropertyAssertion(<#PersonAge> <#Dave> "7"^^xsd:integer)
+DataPropertyAssertion(<#PersonName> <#Dave> "Dave"^^xsd:string)

**Comment by mbehrooz** [comment]
So I believe whatever made that happen, is either in the related plugin or the process in which that related plugin accesses and reads ontology. I would also make sure that this actually was an error, as it is easy for me for example to just enter male and female mistakenly which could happen if the"spouse" is already in ontology with the wrong gender, I believe.

**Comment by candysidner** [comment]
okay, I'll see if I can reproduce this problem next time I do testing (next Monday).  I've assigned myself as responsible for now.
