### ISSUE TITLE
Flag to end game in Rummy, Checkers

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#190]
We need some way to force the end of game (win or lose) for Rummy and Checkers so we can test the conversational logic.

I suggestion a debugging flag in each such as (note capital B!):

```
public static Boolean TEST;
```

which can be set to Boolean.TRUE or FALSE to win/lose.   Then check this flag for non-null somewhere appropriate in each game logic.

This can be set dynamically in the Disco console window for the activity via:

> eval edu.wpi.always.checkers.TEST = true;

**Comment by mbehrooz** [comment]
I have a copied code that sets checkers for example to have only one piece for user so that agent wins with only one move. (that is one line to edit) I used that last week (Jan 10s) to debug checkers. I will look into creating this flag for it which is more structural, but for my own use I already do this. Thanks a lot for pointing it out.
