### ISSUE TITLE
Calendar Issue

### ISSUE THREAD

**Issue by raggroupkathleen** [always-on/always#264]
When you try to add an event, you have the option to enter something but no box comes up to actually type it in. 

The same thing happens if you want to change to event to something else.

**Comment by charlesrich** [comment]
@mbehrooz, hopefully this is enough description to find the problem?

**Comment by mbehrooz** [comment]
It should yes, I will investigate it. Thanks.

**Comment by mbehrooz** [comment]
So the issue is this: the keyboard plugin does not show up while in the calendar. As far as I check in Java, keyboard message is sent. Inside .Net, I am not sure how would this work. My guess that I am investigating now is that the Calendar UI is set up in a way that prevents another layer to come on top of it? I am writing this to see if anyone has a better guess. To reproduce, simply choose "something else" as an event type...
