### ISSUE TITLE
Timing improvement

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#267]
@mbehrooz I tweaked the thinking gaze to make it less strong, especially with the new eye gaze animation.   However, this makes it take less time, so that the click for the agent's move happens _before_ she finishes looking all the way over to the board, which is bad.

Is there perhaps some delay you can change for this?

And since this code is unfortunately not abstacted in SGF ;-(, please check all games.

**Comment by mbehrooz** [comment]
Sure, so there is a AGENT_PLAY_DELAY_AMOUNT and also a AGENT_PLAYING_GAZE_DELAY_AMOUNT. The former is the amount of time since T0 (start of agent turn) that agent will be looking back to board (T0 + AGENT_PLAY_DELAY_AMOUNT) and the latter is the same logic since T0 for playing the move. So if you decreased the first one by 1 second, the second one should be decreased by 1s too, unless you want to change the time delay "between" gazing at board and playing the move (which is 1 second right now). 

If you are looking for a specific number, I can change it and send the pull. 

Also for other games, for rummy it is way more complicated now and there are many timers (while checked to be robust). So if one changed, other ones have to be very carefully changed. But generally I think the timing in rummy is good right now.

For checkers it is more like TTT so I can change it to a preferred amount too.

Thanks.

**Comment by charlesrich** [comment]
Oh, yeah, this brings back (bad? :-) memories.  Can you please tweak them all for me.  You understand what the goal is.

Tx, -CR

**Comment by mbehrooz** [comment]
Oh not at all, I will tweak TTT and checkers timing and I think rummy is good, but let me know if it is not. What is the time amount you have in mind? it is 3 (to gaze at board (from thinking)) and 4 (to play) seconds right now. 2 and 3? Thanks a lot.

**Comment by charlesrich** [comment]
The goal is to have the move/click happen _after_ her head has had enough time to get to the looking at board position.  It is better if the click is slightly _after_ her head is in position, than slightly before.

**Comment by charlesrich** [comment]
Oh, and the looking away time is fine.

**Comment by mbehrooz** [comment]
Sure definitely, so I will increase the playing delay and send a pull for it. 

Thanks a lot.

**Comment by mbehrooz** [comment]
I sent the pull and it is now 4.5 seconds (.5 more). It looked good to me but if you thought 5 would be better please let me know :) Thanks a lot, Yours, Morteza

**Comment by charlesrich** [comment]
I think the move happens still too soon.  Please increase.

Btw, how does it impact rummy?

While we are on timing, there seems like a very long delay before the menu choices come up, e.g., after her turn.  It can't be computation, can it?   Is there a fixed delay to adjust there?

**Comment by mbehrooz** [comment]
Ok I will set it to 5. 

Rummy has 2 gazes, she looks at board, draws, thinks, looks back and plays. And I think the combination is fine to me.

That one is a time delay too. I recently decreased it for checkers and it went much better. I will decrease it more and for all games in this pull.

Thanks.

**Comment by mbehrooz** [comment]
I sent the request which is for all games, thanks a lot for better timing suggestions :)

**Comment by charlesrich** [comment]
I reviewed the timing on TTT and Checkers.   I would still like a little more time (0.5 sec?) _before_ the agent's move (after her head starts turning).

Also, I don't think there should be any extra delay (or else _very_ little) added before putting up any of the menus.  Let's try this.

Finally, I could not test Rummy, because the game froze at the start, see #273

**Comment by mbehrooz** [comment]
Thanks for testing, definitely, I increased the timing by .5 second. The menu delay cannot be really shorted because that might cause the long agent comments to be cut off. I tested that 3 seconds is good enough. I know that this is not the best design though.

For rummy, as I commented in issue 273, it is most likely that VS was not rebuilt, I tried many times to get the bug but could not, although same thing happened to me yesterday when I did not build. 

Thanks a lot

**Comment by charlesrich** [comment]
That's too bad.  I had assume that the sychronization (BML-like) facilities of the architecture were being used to constrain the menus until after the agent had finished speaking.

But there really is not time to polish this now.  More important to fix bugs in other plugins.

I will close 273.
