### ISSUE TITLE
rummy bug when agent goes first in game

### ISSUE THREAD

**Issue by candysidner** [always-on/always#387]
rummy stops with no apparent problem when you tell it to go first.  I was able to stop it because the stop playing rummy button was on the screen.  I did check the state of the computer.  No process was using much of the CPU (about 25% total by Java, plugins and dvm).

When I tried playing rummy later, there were no menus and nothing happened.

Note that when I played rummy in a new run, and I said I would go first I had no problems.

**Comment by charlesrich** [comment]
@mbehrooz @charlesrich

I verified that this is reproducible exactly as Candy describes it, including no menus when starting to play the second time after bug at first.    This is definitely weird, because SRummySchema should entirely start with a fresh state when it starts a new game.

Btw, having the agent go first in TTT works fine.

**Comment by mbehrooz** [comment]
This is obviously new, I had tested these extensively. I will look at it, but any information as for what changed in MenuStateMachine will help. Thanks.

**Comment by mbehrooz** [comment]
It is fixed :)
