### ISSUE TITLE
About running very slow

### ISSUE THREAD

**Issue by candysidner** [always-on/always#390]
I did a several additions to the calendar, talked to the agent on explain and then talked with agent about f/f.  That plugin ran slower and slower as more friends were discussed until finally it stopped putting up menus.  System usage showed 76-85% of CPU to Java, rest ot plugins and dvm.  Session Schema Java window said not responding.

https://www.dropbox.com/s/b4ulq2a6521qypi/User.2014-06-05_14_55_03.txt
https://www.dropbox.com/s/huh57ggaylr6mgj/User.2014-06-05_14_55_03.owl

**Comment by charlesrich** [comment]
@candysidner 

There is an exception at the end of the log file, but unfortunately it is not fully printed out (not sure why---could be because system was running so slow):

}Exception in thread "edu.wpi.disco.rt.realizer.FocusRequestRealizer" 

Disposing of edu.wpi.always.about.AboutSchema@3c403c5f...java.lang.NullPointerExceptionException in thread "AWT-Event

Please try to reproduce this error again.

-CR
